### ISSUE TITLE
Сразу не заработало на ЗУП КОРП

### ISSUE THREAD

**Issue by YuryBatiaev** [korotovskih/m10n_reprieve#2]
Добрый день!
Тут сразу нужен Интернет. Для закрытых организаций так не сработает. Проверенные адреса безопасность открывает, не все подряд.
Что предпринять?
Кстати предлагаю использовать номера версий нестандартной формы, как то ГГММДД.NNN, где ГГ-год, ММ-месяц, ДД-день, NNN - номер версии от 001 до 999. К примеру, " m10n_reprieve_220929_002.cfe" 
С уважением, Юрий

**Comment by tseziy** [comment]
Добрый день, Юрий!
Интернет требуется только для обновления расширения. Для остальное работы интернет не нужен. 
Про ошибку со скрина знаем, выпустим фикс в ближайшее время

**Comment by korotovskih** [comment]
Здравствуйте

1. Ошибку: "Предопределенный элемент не существует" - исправили в версии 1.0.2, уже вышла
2. Про интернет, он не нужен для основной функции, но используется для проверки обновлений расширения - ничего страшного, что его нет. Сделаем в следующей версии проверку обновлений менее болезненной для вас.
3. Подумаем про дата версионирование, надеюсь тема потеряет актуальность =)

**Comment by korotovskih** [comment]
1
