### ISSUE TITLE
Ошибка ЗУП КОРП 3.1.23.68

### ISSUE THREAD

**Issue by Borisskin** [korotovskih/m10n_reprieve#3]
Для указанной версии имена предопределённых элементов в справочнике НаборыДополнительныхРеквизитовИСведений изменены на "Удалить...".

В модуле объекта обработки МИтСвойства можно сделать проверку на версию конфигурации и дополнять ИмяПредопределенногоНабора

У себя быстренько добавил следующее:
`Функция _НайтиНабор(ИмяПредопределенногоНабора) Экспорт
	Если ЭтоЗупКорпСтаршейВерсии() И Лев(ИмяПредопределенногоНабора, 10) = "Справочник" Тогда
		ИмяПредопределенногоНабора = СтрШаблон("Удалить%1", ИмяПредопределенногоНабора);
	КонецЕсли;
......
КонецФункции

Функция ЭтоЗупКорпСтаршейВерсии()
	
	Если _Конфигурация = "ЗарплатаИУправлениеПерсоналомКОРП" И _ВерсияКонфигурации = "3.1.23.68" Тогда
		Возврат Истина;
	Иначе
		Возврат Ложь;
	КонецЕсли;
	
КонецФункции`

**Comment by Borisskin** [comment]
Пока писал и правил - уже исправили ошибку? :)

**Comment by tseziy** [comment]
> Пока писал и правил - уже исправили ошибку? :)

Да, обновите и проверьте)

**Comment by Borisskin** [comment]
Поправлено, спасибо.
